sonar.projectKey=taller-sast_analisis-vulnerabilidades
sonar.projectName=analisis-vulnerabilidades
sonar.projectVersion=1.0
sonar.sources=backend,frontend
sonar.language=js
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/node_modules/**
sonar.javascript.lcov.reportPaths=
